apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-content
data:
  index.html: |
    <html>
    <head><title>Apache Hello</title></head>
    <body>
      <h1>Hello from Apache on Kubernetes</h1>
    </body>
    </html>
