apiVersion: v1
kind: Pod
metadata:
  name: log-collector
  labels:
    app: log-collector
spec:
  containers:
    - name: log-collector
      image: log-collector:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 10
