apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-sidecar
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21
    ports:
      - containerPort: 80
    volumeMounts:
      - name: nginx-logs
        mountPath: /var/log/nginx
    # Nginx by default logs to /var/log/nginx/access.log and error.log

  - name: log-sidecar
    image: busybox
    command: ["/bin/sh", "-c"]
    # This sidecar will continuously print the access log of Nginx
    args: ["tail -n+1 -f /var/log/nginx/access.log"]
    volumeMounts:
      - name: nginx-logs
        mountPath: /var/log/nginx

  # Define a shared volume for logs
  volumes:
  - name: nginx-logs
    emptyDir: {}
