apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-extended-sidecars
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10

  - name: log-sidecar
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["tail -n+1 -f /var/log/nginx/access.log"]
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
    # Optional readiness probe: checks if log file is present/non-empty
    readinessProbe:
      exec:
        command: ["test", "-s", "/var/log/nginx/access.log"]
      initialDelaySeconds: 5
      periodSeconds: 5
    # Optional liveness probe: ensures the tailing process continues to run
    livenessProbe:
      exec:
        command: ["pidof", "tail"]
      initialDelaySeconds: 10
      periodSeconds: 10

  - name: log-forwarder
    image: curlimages/curl
    command: ["/bin/sh", "-c"]
    # Example: forward the logs every few seconds to a remote endpoint
    args: ["while true; do cat /var/log/nginx/access.log | curl -X POST -H 'Content-Type: text/plain' --data-binary @- http://log-collector.example.com; sleep 10; done"]
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
    # Readiness probe: checks remote service connectivity
    readinessProbe:
      exec:
        command: ["curl", "-f", "http://log-collector.example.com/health"]
      initialDelaySeconds: 5
      periodSeconds: 10
    # Liveness probe: ensures container is functioning
    livenessProbe:
      exec:
        command: ["pidof", "sh"]
      initialDelaySeconds: 10
      periodSeconds: 10

  volumes:
  - name: nginx-logs
    emptyDir: {}
