apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: caching-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379
        # For a simple demo, no password, no persistence configured
        # In production, add password, configs, and persistent volumes.
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: caching-demo
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
