apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: caching-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: app-a:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-a
  namespace: caching-demo
spec:
  type: ClusterIP
  selector:
    app: app-a
  ports:
  - port: 5000
    targetPort: 5000
