apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  namespace: caching-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b
        image: app-b:v1
        imagePullPolicy: Never
        env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: APP_A_HOST
            value: "app-a"
          - name: APP_A_PORT
            value: "5000"
          - name: CACHE_TTL
            value: "300"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-b
  namespace: caching-demo
spec:
  type: ClusterIP
  selector:
    app: app-b
  ports:
  - port: 5000
    targetPort: 5000
